// <auto-generated />
using System;
using ECommerce.IA.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace ECommerce.IA.Api.Migrations
{
    [DbContext(typeof(IADbContext))]
    [Migration("20260304001334_AddQueryCache")]
    partial class AddQueryCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.IA.Api.Entities.QueryCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pergunta");

                    b.Property<string>("SqlGerado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_gerado");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean")
                        .HasColumnName("sucesso");

                    b.HasKey("Id");

                    b.ToTable("query_cache", (string)null);
                });

            modelBuilder.Entity("ECommerce.IA.Api.Entities.SchemaEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("banco");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tabela");

                    b.HasKey("Id");

                    b.ToTable("schema_embeddings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
